/*
 * uart_cmds_handle.h
 *
 *  Created on: Jan 13, 2025
 *      Author: yuchung886
 */

#ifndef INC_UART_CMDS_HANDLE_H_
#define INC_UART_CMDS_HANDLE_H_

#define UART_CMDS_HANDLE_ROUTINES_MIN_PERIOD_US		10000

#define CMD_HEADER_INDEX				0
#define CMD_HEADER_CHAR					0x5A

#define CMD_CODE_INDEX							1
#define CMD_CODE__GET_FW_VER					0x01
#define CMD_CODE__GET_FIRE_CTRL_STATUS			0x02
#define CMD_CODE__SET_FIRE_COUNT				0x03
#define CMD_CODE__SET_FIRE_CTRL_CONFIG			0x04
#define CMD_CODE__SET_FIRE_SAFETY				0x05
#define CMD_CODE__SET_AMMO_FEEDER_CONFIG		0x06
#define CMD_CODE__SET_AMMO_FEEDING				0x07
#define CMD_CODE__GET_PAN_TILT_STEP_ANGLE		0x08
#define CMD_CODE__GET_PAN_TILT_CURR_ANGLE		0x09
#define CMD_CODE__SET_PAN_TILT_ROTATE_ANGLE		0x0A
#define CMD_CODE__GET_TOF_SENSROS_CTRL_STATUS	0x0B
#define CMD_CODE__SET_RADAR_EN					0x0C
#define CMD_CODE__SET_RADAR_CONFIG				0x0D
#define CMD_CODE__GET_RADAR_RANGING				0x0E
#define CMD_CODE__GET_AIMING_DISTANCE			0x0F
#define CMD_CODE__SET_SEARCHLIGHT_PWM			0x10

#define CMD_PARAMS_INDEX								2
#define CMD_PARAMS_LENGTH__GET_FIRE_CTRL_STATUS			1
#define CMD_PARAMS_LENGTH__GET_FW_VER					15
#define CMD_PARAMS_LENGTH__SET_FIRE_COUNT				1
#define CMD_PARAMS_LENGTH__SET_FIRE_CTRL_CONFIG			3
#define CMD_PARAMS_LENGTH__SET_FIRE_SAFETY				1
#define CMD_PARAMS_LENGTH__SET_AMMO_FEEDER_CONFIG		1
#define CMD_PARAMS_LENGTH__SET_AMMO_FEEDING				3
#define CMD_PARAMS_LENGTH__GET_PAN_TILT_STEP_ANGLE		4
#define CMD_PARAMS_LENGTH__GET_PAN_TILT_CURR_ANGLE		4
#define CMD_PARAMS_LENGTH__SET_PAN_TILT_ROTATE_ANGLE	4
#define CMD_PARAMS_LENGTH__GET_TOF_SENSROS_CTRL_STATUS	1
#define CMD_PARAMS_LENGTH__SET_RADAR_EN					1
#define CMD_PARAMS_LENGTH__SET_RADAR_CONFIG				1
#define CMD_PARAMS_LENGTH__GET_RADAR_RANGING			36
#define CMD_PARAMS_LENGTH__GET_AIMING_DISTANCE			1
#define CMD_PARAMS_LENGTH__SET_SEARCHLIGHT_PWM			1

extern uint8_t uart_rx_buf[];

#define ACK_HEADER_INDEX	0
#define ACK_HEADER_CHAR		0x5A

#define ACK_CODE_INDEX		1
#define ACK_CODE__SUCCESS	0x00

#define ACK_PARAMS_INDEX	2

uint8_t uart_cmds_handle_perodic_routines();

#endif /* INC_UART_CMDS_HANDLE_H_ */
